// <auto-generated />
using System;
using GameService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameService.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameDataLibrary.BoardGameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PublishersId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublishersId");

                    b.ToTable("BoardGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9622),
                            Description = "Control one fantasy race after another to expand throught the land",
                            ImageURL = "https://cf.geekdo-images.com/aoPM07XzoceB-RydLh08zA__imagepage/img/lHmv0ddOrUvpiLcPeQbZdT5yCEA=/fit-in/900x600/filters:no_upscale():strip_icc()/pic428828.jpg",
                            Name = "SmallWorld",
                            PublishersId = 1,
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9623)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9624),
                            Description = "Attract a beautiful and diversecollection of birds to your wildlife preserve.",
                            ImageURL = "https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__imagepagezoom/img/yS4vL6iTCvHSvGySxyOjV_-R3dI=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic4458123.jpg",
                            Name = "WingSpan",
                            PublishersId = 2,
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9625)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9626),
                            Description = "Hasbro Gaming Trouble Board Game for Kids Ages 5 and Up 2-4 Players",
                            ImageURL = "https://m.media-amazon.com/images/I/81MdgnO4l9L._AC_UL400_.jpg",
                            Name = "Trouble",
                            PublishersId = 3,
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9627)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9629),
                            Description = "Hasbro Gaming The Game of Life Board Game Ages 8 & Up",
                            ImageURL = "https://m.media-amazon.com/images/I/81yQxkx3vwL._AC_UL640_QL65_.jpg",
                            Name = "The Game of Life",
                            PublishersId = 3,
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9629)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9631),
                            Description = "Hasbro Gaming Candy Land Kingdom Of Sweet Adventures Board Game For Kids Ages",
                            ImageURL = "https://m.media-amazon.com/images/I/91yUG40gv0L._AC_UL400_.jpg",
                            Name = "Candy Land",
                            PublishersId = 3,
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9631)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9633),
                            Description = "Hasbro Gaming Risk Military Wargame",
                            ImageURL = "https://m.media-amazon.com/images/I/91jsvpbPP3L._AC_UL400_.jpg",
                            Name = "Risk",
                            PublishersId = 3,
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9633)
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9635),
                            Description = "Ticket to Ride Board Game | Family Board Game | Board Game for Adults and Family",
                            ImageURL = "https://m.media-amazon.com/images/I/91YNJM4oyhL._AC_UL400_.jpg",
                            Name = "Ticket to ride",
                            PublishersId = 1,
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9635)
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9637),
                            Description = "SORRY Classic Family Board Game Indoor Outdoor Retro Party Activity Summer Toy with Oversized Gameboard",
                            ImageURL = "https://m.media-amazon.com/images/I/81ItkRyOaaL._AC_UL400_.jpg",
                            Name = "Sorry",
                            PublishersId = 4,
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9638)
                        });
                });

            modelBuilder.Entity("GameDataLibrary.PublisherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9307),
                            Name = "Days of Wonder",
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9313)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9315),
                            Name = "Stonemaier Games",
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9315)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9317),
                            Name = "Hasbro",
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9317)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9318),
                            Name = "Spin Master",
                            UpdateDate = new DateTime(2024, 2, 15, 19, 37, 1, 841, DateTimeKind.Utc).AddTicks(9319)
                        });
                });

            modelBuilder.Entity("GameDataLibrary.BoardGameModel", b =>
                {
                    b.HasOne("GameDataLibrary.PublisherModel", "Publishers")
                        .WithMany("BoardGames")
                        .HasForeignKey("PublishersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publishers");
                });

            modelBuilder.Entity("GameDataLibrary.PublisherModel", b =>
                {
                    b.Navigation("BoardGames");
                });
#pragma warning restore 612, 618
        }
    }
}
